export struct GruvboxPalette {
    fg: brush,
    fg0: brush,
    fg1: brush,
    fg2: brush,
    fg3: brush,
    fg4: brush,

    bg: brush,
    bg0-hard: brush,
    bg0-soft: brush,
    bg0: brush,
    bg1: brush,
    bg2: brush,
    bg3: brush,
    bg4: brush,

    fg-red: brush,
    fg-green: brush,
    fg-yellow: brush,
    fg-blue: brush,
    fg-purple: brush,
    fg-aqua: brush,
    fg-orange: brush,
    fg-gray: brush,

    hl-red: brush,
    hl-green: brush,
    hl-yellow: brush,
    hl-blue: brush,
    hl-purple: brush,
    hl-aqua: brush,
    hl-orange: brush,
    hl-gray: brush,

    gray: brush,
}

export enum AccentName {
    Red, Green, Yellow, Blue, Purple, Aqua, Orange
}

export struct AccentShades {
    neutral: brush,
    bright: brush,
    faded: brush,
}

export struct SchemeAccent {
    default: brush,
    secondary: brush,
    tertiary: brush,
}

export global SchemeSelector  {
    in property <bool> dark-color-scheme: true;
    in property <AccentName> primary-accent: Aqua;

    public pure function gruvbox-palette(dark: bool) -> GruvboxPalette {{
        fg: dark ? Colors.light1 : Colors.dark1,
        fg0: dark ? Colors.light0 : Colors.dark0,
        fg1: dark ? Colors.light1 : Colors.dark1,
        fg2: dark ? Colors.light2 : Colors.dark2,
        fg3: dark ? Colors.light3 : Colors.dark3,
        fg4: dark ? Colors.light4 : Colors.dark4,

        bg: dark ? Colors.dark0 : Colors.light0,
        bg0-hard: dark ? Colors.dark0-hard : Colors.light0-hard,
        bg0-soft: dark ? Colors.dark0-soft : Colors.light0-soft,
        bg0: dark ? Colors.dark0 : Colors.light0,
        bg1: dark ? Colors.dark1 : Colors.light1,
        bg2: dark ? Colors.dark2 : Colors.light2,
        bg3: dark ? Colors.dark3 : Colors.light3,
        bg4: dark ? Colors.dark4 : Colors.light4,

        fg-red: dark ? Colors.bright-red : Colors.faded-red,
        fg-green: dark ? Colors.bright-green : Colors.faded-green,
        fg-yellow: dark ? Colors.bright-yellow : Colors.faded-yellow,
        fg-blue: dark ? Colors.bright-blue : Colors.faded-blue,
        fg-purple: dark ? Colors.bright-purple : Colors.faded-purple,
        fg-aqua: dark ? Colors.bright-aqua : Colors.faded-aqua,
        fg-orange: dark ? Colors.bright-orange : Colors.faded-orange,
        fg-gray: dark ? Colors.gray-245 : Colors.gray-244,

        hl-red: Colors.neutral-red,
        hl-green: Colors.neutral-green,
        hl-yellow: Colors.neutral-yellow,
        hl-blue: Colors.neutral-blue,
        hl-purple: Colors.neutral-purple,
        hl-aqua: Colors.neutral-aqua,
        hl-orange: Colors.neutral-orange,
        hl-gray: dark ? Colors.light4 : Colors.gray-244,

        gray: dark ? Colors.gray-245 : Colors.gray-244,
    }}

    public pure function shades-of(color: AccentName) -> AccentShades {
        if (color == AccentName.Red) {
            GlobalAccents.red
        } else if (color == AccentName.Green) {
            GlobalAccents.green
        } else if (color == AccentName.Yellow) {
            GlobalAccents.yellow
        } else if (color == AccentName.Blue) {
            GlobalAccents.blue
        } else if (color == AccentName.Purple) {
            GlobalAccents.purple
        } else if (color == AccentName.Aqua) {
            GlobalAccents.aqua
        } else if (color == AccentName.Orange) {
            GlobalAccents.orange
        } else {{
            neutral: #FF0000,
            bright: #00FF00,
            faded: #00FFFF,
        }}
    }

    public pure function accents-of(dark: bool, color: AccentName) -> SchemeAccent {
        dark ? {
            default: shades-of(color).bright,
            secondary: shades-of(color).neutral,
            tertiary: shades-of(color).faded,
        } : {
            default: shades-of(color).faded,
            secondary: shades-of(color).bright,
            tertiary: shades-of(color).neutral,
        }
    }
}

export global Colors {
    out property <brush> dark0-hard: #1d2021;
    out property <brush> dark0: #282828;
    out property <brush> dark0-soft: #32302f;
    out property <brush> dark1: #3c3836;
    out property <brush> dark2: #504945;
    out property <brush> dark3: #665c54;
    out property <brush> dark4: #7c6f64;
    out property <brush> dark4-256: #7c6f64;

    out property <brush> gray-245: #928374;
    out property <brush> gray-244: #928374;

    out property <brush> light0-hard: #f9f5d7;
    out property <brush> light0: #fbf1c7;
    out property <brush> light0-soft: #f2e5bc;
    out property <brush> light1: #ebdbb2;
    out property <brush> light2: #d5c4a1;
    out property <brush> light3: #bdae93;
    out property <brush> light4: #a89984;
    out property <brush> light4-256: #a89984;

    out property <brush> bright-red: #fb4934;
    out property <brush> bright-green: #b8bb26;
    out property <brush> bright-yellow: #fabd2f;
    out property <brush> bright-blue: #83a598;
    out property <brush> bright-purple: #d3869b;
    out property <brush> bright-aqua: #8ec07c;
    out property <brush> bright-orange: #fe8019;

    out property <brush> neutral-red: #cc241d;
    out property <brush> neutral-green: #98971a;
    out property <brush> neutral-yellow: #d79921;
    out property <brush> neutral-blue: #458588;
    out property <brush> neutral-purple: #b16286;
    out property <brush> neutral-aqua: #689d6a;
    out property <brush> neutral-orange: #d65d0e;

    out property <brush> faded-red: #9d0006;
    out property <brush> faded-green: #79740e;
    out property <brush> faded-yellow: #b57614;
    out property <brush> faded-blue: #076678;
    out property <brush> faded-purple: #8f3f71;
    out property <brush> faded-aqua: #427b58;
    out property <brush> faded-orange: #af3a03;
}

export global GlobalPalette {
    in-out property <bool> dark: SchemeSelector.dark-color-scheme;
    out property <GruvboxPalette> palette: SchemeSelector.gruvbox-palette(dark);

    out property <brush> fg: palette.fg;
    out property <brush> fg0: palette.fg0;
    out property <brush> fg1: palette.fg1;
    out property <brush> fg2: palette.fg2;
    out property <brush> fg3: palette.fg3;
    out property <brush> fg4: palette.fg4;

    out property <brush> bg: palette.bg;
    out property <brush> bg0-hard: palette.bg0-hard;
    out property <brush> bg0-soft: palette.bg0-soft;
    out property <brush> bg0: palette.bg0;
    out property <brush> bg1: palette.bg1;
    out property <brush> bg2: palette.bg2;
    out property <brush> bg3: palette.bg3;
    out property <brush> bg4: palette.bg4;

    out property <brush> fg-red: palette.fg-red;
    out property <brush> fg-green: palette.fg-green;
    out property <brush> fg-yellow: palette.fg-yellow;
    out property <brush> fg-blue: palette.fg-blue;
    out property <brush> fg-purple: palette.fg-purple;
    out property <brush> fg-aqua: palette.fg-aqua;
    out property <brush> fg-orange: palette.fg-orange;
    out property <brush> fg-gray: palette.fg-gray;

    out property <brush> hl-red: palette.hl-red;
    out property <brush> hl-green: palette.hl-green;
    out property <brush> hl-yellow: palette.hl-yellow;
    out property <brush> hl-blue: palette.hl-blue;
    out property <brush> hl-purple: palette.hl-purple;
    out property <brush> hl-aqua: palette.hl-aqua;
    out property <brush> hl-orange: palette.hl-orange;
    out property <brush> hl-gray: palette.hl-gray;

    out property <brush> gray: palette.gray;
}

export global GlobalAccents {
    in-out property <bool> dark-color-scheme: SchemeSelector.dark-color-scheme;
    in-out property <AccentName> primary-accent: SchemeSelector.primary-accent;

    out property <AccentShades> red: {
        neutral: Colors.neutral-red,
        bright: Colors.bright-red,
        faded: Colors.faded-red,
    };
    out property <AccentShades> green: {
        neutral: Colors.neutral-green,
        bright: Colors.bright-green,
        faded: Colors.faded-green,
    };
    out property <AccentShades> yellow: {
        neutral: Colors.neutral-yellow,
        bright: Colors.bright-yellow,
        faded: Colors.faded-yellow,
    };
    out property <AccentShades> blue: {
        neutral: Colors.neutral-blue,
        bright: Colors.bright-blue,
        faded: Colors.faded-blue,
    };
    out property <AccentShades> purple: {
        neutral: Colors.neutral-purple,
        bright: Colors.bright-purple,
        faded: Colors.faded-purple,
    };
    out property <AccentShades> aqua: {
        neutral: Colors.neutral-aqua,
        bright: Colors.bright-aqua,
        faded: Colors.faded-aqua,
    };
    out property <AccentShades> orange: {
        neutral: Colors.neutral-orange,
        bright: Colors.bright-orange,
        faded: Colors.faded-orange,
    };
}
