import { MaterialPalette, MaterialScheme, AccentScheme } from "../material-palette.slint";
import { ButtonStyle, StyleFactory } from "style/global.slint";
import { ControlSize, ControlTheme } from "style/metrics.slint";



export component Button {
  in property <AccentScheme> base-accent: MaterialScheme.base-accent;
  in property <AccentScheme> accent: MaterialScheme.base-accent;


  in property <bool> filled: false;
  in property <ControlSize> size: ControlSize.Medium;
  in property <ControlTheme> theme: ControlTheme.Rounded;

  in property <ButtonStyle> style: StyleFactory.button(filled, size, theme);

  in-out property <string> text <=> i-label.text;
  in-out property <bool> enabled: true;

  out property <bool> pressed: self.enabled && i-touch-area.pressed;

  width: i-label.width + style.padding-x * 2 + style.margin-x * 2;
  height: i-label.height + style.depress + style.padding-y * 2 + style.margin-y * 2;

  i-box := Rectangle {
    x: root.width / 2 - self.width / 2;
    y: root.height / 2 - self.height / 2;

    width: root.width - style.margin-x * 2;
    height: root.height - style.margin-y * 2;

    i-bottom := Rectangle {
      y: style.depress;

      width: i-background.width;
      height: i-background.height;

      background: accent.fg4;

      border-radius: style.border-radius;

      drop-shadow-color: accent.fg3;
      drop-shadow-blur: style.shadow-blur;
    }

    i-background := Rectangle {
      y: 0;
      animate y {
        duration: style.depress-duration;
        easing: ease-in;
      }

      width: i-label.width + style.padding-x * 2;
      height: i-label.height + style.padding-y * 2;

      background: filled ? accent.bg2 : base-accent.bg1;

      border-color: accent.fg2;
      border-width: style.border-width;
      border-radius: style.border-radius;

      i-label := Text {
        color: !style.accent-text || filled ? base-accent.fg0 : accent.fg0;

        font-family: style.font-family;
        font-size: style.font-size;
        font-weight: style.font-weight;

        text: "Button";
      }
    }
  }

  i-touch-area := TouchArea {}

  states [
    disabled when !root.enabled : {
      root.opacity: 0.5;
    }
    pressed when root.pressed : {
      i-background.y: style.depress / 2;
    }
    hover when i-touch-area.has-hover : {
      i-bottom.background: accent.fg2; // Lighten from 4 to 2
      i-bottom.drop-shadow-color: accent.fg4; // Darken from 3 to 4
      i-background.background: filled ? accent.bg3 : base-accent.bg2; // Lighten from 2 to 3
      i-background.border-color: accent.fg1; // Lighten from 2 to 1
      // i-label.color: filled ? base-accent.fg0 : accent.fg0;
    }
  ]
}

import { GridBox , VerticalBox, ScrollView } from "std-widgets.slint";

export component ButtonPaletteTableDisplay inherits Rectangle {
  // width: 300px;
  // height: 500px;
  background: MaterialScheme.base-accent.bg1;

  ScrollView {
    HorizontalLayout {
      for dark in [true, false] : Rectangle {
        background: MaterialScheme.scheme(dark, "grey").bg0;

        HorizontalLayout {
          for theme in [ControlTheme.Boxy, ControlTheme.Rounded] : HorizontalLayout {
          for size in [ControlSize.Small, ControlSize.Medium, ControlSize.Large] : HorizontalLayout {
              for filled in [true, false] : VerticalLayout {
              for color in MaterialPalette.colors: Button {
                  base-accent: MaterialScheme.scheme(dark, "grey");
                  accent: MaterialScheme.scheme(dark, color);
                  // enabled: enabled;
                  filled: filled;
                  size: size;
                  theme: theme;
                }
              }
            }
          }
        }
      }
    }
  }
}
