import { MaterialPalette, MaterialScheme, AccentScheme } from "../material-palette.slint";
import { GlobalStyle, ButtonStyle } from "style/global.slint";

export component Button {
  in property <AccentScheme> base-accent: MaterialScheme.base-accent;
  in property <AccentScheme> accent: MaterialScheme.base-accent;

  in-out property <bool> filled: style.filled;
  in-out property <bool> boxy-style: false;
  in property <ButtonStyle> style: boxy-style ? GlobalStyle.button-boxy : GlobalStyle.button;

  in-out property <string> text <=> i-label.text;
  in-out property <bool> enabled: true;

  out property <bool> pressed: self.enabled && i-touch-area.pressed;

  width: i-label.width + style.padding-x * 2 + style.margin-x * 2;
  height: i-label.height + style.depress + style.padding-y * 2 + style.margin-y * 2;

  i-box := Rectangle {
    x: root.width / 2 - self.width / 2;
    y: root.height / 2 - self.height / 2;

    width: root.width - style.margin-x * 2;
    height: root.height - style.margin-y * 2;

    i-bottom := Rectangle {
      y: style.depress;

      width: i-background.width;
      height: i-background.height;

      background: accent.fg4;

      border-radius: style.border-radius;

      drop-shadow-color: accent.fg3;
      drop-shadow-blur: style.shadow-blur;
    }

    i-background := Rectangle {
      y: 0;

      width: i-label.width + style.padding-x * 2;
      height: i-label.height + style.padding-y * 2;

      background: filled ? accent.bg2 : base-accent.bg1;

      border-color: accent.fg2;
      border-width: style.border-width;
      border-radius: style.border-radius;

      i-label := Text {
        color: !style.accent-text || filled ? base-accent.fg0 : accent.fg0;

        font-family: style.font-family;
        font-size: style.font-size;
        font-weight: style.font-weight;

        text: "Button";
      }
    }
  }

  i-touch-area := TouchArea {}

  states [
    disabled when !root.enabled : {
      root.opacity: 0.5;
    }
    pressed when root.pressed : {
      i-background.y: style.depress / 2;
    }
    hover when i-touch-area.has-hover : {
      i-bottom.background: accent.fg2; // Lighten from 4 to 2
      i-bottom.drop-shadow-color: accent.fg4; // Darken from 3 to 4
      i-background.background: filled ? accent.bg3 : base-accent.bg2; // Lighten from 2 to 3
      i-background.border-color: accent.fg1; // Lighten from 2 to 1
      // i-label.color: filled ? base-accent.fg0 : accent.fg0;
    }
  ]
}

import { GridBox , VerticalBox, ScrollView } from "std-widgets.slint";

export component ButtonPaletteVerticalDisplay inherits VerticalBox {
  in property <bool> dark-color-scheme: true;
  in property <bool> boxy-style: false;
  in property <ButtonStyle> style: boxy-style ? GlobalStyle.button-boxy : GlobalStyle.button;

  in property <bool> enabled: true;
  in property <bool> filled: true;

  for color in MaterialPalette.colors: Button {
    style: style;
    boxy-style: boxy-style;
    base-accent: MaterialScheme.scheme(dark-color-scheme, "grey");
    accent: MaterialScheme.scheme(dark-color-scheme, color);
    enabled: enabled;
    filled: filled;
  }
}

export component ButtonPaletteTableDisplay inherits Rectangle {
  // width: 300px;
  // height: 500px;
  background: MaterialScheme.base-accent.bg1;

  ScrollView {
    VerticalLayout {
      Button {
        text: "Ooga booga!";
      }

      HorizontalLayout {
        Rectangle {
          background: MaterialScheme.scheme(true, "grey").bg0;
          HorizontalLayout {
            ButtonPaletteVerticalDisplay { dark-color-scheme: true; boxy-style: true; }
            ButtonPaletteVerticalDisplay { dark-color-scheme: true; boxy-style: true; filled: false; }
          }
        }
        Rectangle {
          background: MaterialScheme.scheme(false, "grey").bg0;
          HorizontalLayout {
            ButtonPaletteVerticalDisplay { dark-color-scheme: false; boxy-style: true; }
            ButtonPaletteVerticalDisplay { dark-color-scheme: false; boxy-style: true; filled: false; }
          }
        }
        Rectangle {
          background: MaterialScheme.scheme(true, "grey").bg0;
          HorizontalLayout {
            // ButtonPaletteVerticalDisplay { dark-color-scheme: true; boxy-style: true; enabled: false; }
            // ButtonPaletteVerticalDisplay { dark-color-scheme: true; boxy-style: true; filled: false; enabled: false; }
          }
        }
        Rectangle {
          background: MaterialScheme.scheme(false, "grey").bg0;
          HorizontalLayout {
            // ButtonPaletteVerticalDisplay { dark-color-scheme: false; boxy-style: true; enabled: false; }
            // ButtonPaletteVerticalDisplay { dark-color-scheme: false; boxy-style: true; filled: false; enabled: false; }
          }
        }
      }

      HorizontalLayout {
        Rectangle {
          background: MaterialScheme.scheme(true, "grey").bg0;
          HorizontalLayout {
            ButtonPaletteVerticalDisplay { dark-color-scheme: true; }
            ButtonPaletteVerticalDisplay { dark-color-scheme: true; filled: false; }
          }
        }
        Rectangle {
          background: MaterialScheme.scheme(false, "grey").bg0;
          HorizontalLayout {
            ButtonPaletteVerticalDisplay { dark-color-scheme: false; }
            ButtonPaletteVerticalDisplay { dark-color-scheme: false; filled: false; }
          }
        }
        Rectangle {
          background: MaterialScheme.scheme(true, "grey").bg0;
          HorizontalLayout {
            // ButtonPaletteVerticalDisplay { dark-color-scheme: true; enabled: false; }
            // ButtonPaletteVerticalDisplay { dark-color-scheme: true; filled: false; enabled: false; }
          }
        }
        Rectangle {
          background: MaterialScheme.scheme(false, "grey").bg0;
          HorizontalLayout {
            // ButtonPaletteVerticalDisplay { dark-color-scheme: false; enabled: false; }
            // ButtonPaletteVerticalDisplay { dark-color-scheme: false; filled: false; enabled: false; }
          }
        }
      }

    }
  }
}
