import { ControlSize, ControlTheme } from "metrics.slint";

export struct ButtonStyle {
  border-width: length,
  border-radius: length,
  filled: bool,
  font-family: string,
  font-size: length,
  font-weight: int,
  accent-text: bool,
  margin-x: length,
  margin-y: length,
  padding-x: length,
  padding-y: length,
  depress: length,
  // depress-easing: easing,
  depress-duration: duration,
  shadow-blur: length,
}

export global StyleFactory {
  public pure function button(filled: bool, size: ControlSize, theme: ControlTheme) -> ButtonStyle {
    {
      filled: filled,
      font-size:
        size == ControlSize.Large ? 18px
        : size == ControlSize.Medium ? 16px
        : size == ControlSize.Small ? 12px : 0,
      font-weight:
        size == ControlSize.Large ? 500
        : size == ControlSize.Medium ? 500
        : size == ControlSize.Small ? 400 : 0,
      border-width:
        theme == ControlTheme.Rounded ? 0
        : size == ControlSize.Large ? 3px
        : size == ControlSize.Medium ? 2px
        : size == ControlSize.Small ? 1px : 0,
      border-radius:
        theme == ControlTheme.Boxy ? 0
        : size == ControlSize.Large ? 7px
        : size == ControlSize.Medium ? 5px
        : size == ControlSize.Small ? 3px : 0,
      margin-x:
        size == ControlSize.Large ? 8px
        : size == ControlSize.Medium ? 4px
        : size == ControlSize.Small ? 3px : 0,
      margin-y:
        size == ControlSize.Large ? 8px
        : size == ControlSize.Medium ? 4px
        : size == ControlSize.Small ? 3px : 0,
      padding-x:
        size == ControlSize.Large ? 18px
        : size == ControlSize.Medium ? 14px
        : size == ControlSize.Small ? 10px : 0,
      padding-y:
        size == ControlSize.Large ? 10px
        : size == ControlSize.Medium ? 6px
        : size == ControlSize.Small ? 3px : 0,
      font-family: "",
        // size == ControlSize.Large ? 0
        // : size == ControlSize.Medium ? 0
        // : size == ControlSize.Small ? 0 : 0,
      accent-text: !filled,
        // size == ControlSize.Large ? 0
        // : size == ControlSize.Medium ? 0
        // : size == ControlSize.Small ? 0 : 0,
      depress:
        size == ControlSize.Large ? 8px
        : size == ControlSize.Medium ? 4px
        : size == ControlSize.Small ? 2px : 0,
      depress-duration: 40ms,
      shadow-blur:
        size == ControlSize.Large ? 4px
        : size == ControlSize.Medium ? 2px
        : size == ControlSize.Small ? 2px : 0,
    };
  }
}
