export struct ButtonStyle {
    border-width: length,
    border-radius: length,
    filled: bool,
    font-family: string,
    font-size: length,
    font-weight: int,
    accent-text: bool,
    margin-x: length,
    margin-y: length,
    padding-x: length,
    padding-y: length,
    depress: length,
    shadow-blur: length,
}

export global GlobalStyle {
    in-out property <bool> dark-color-scheme;

    out property <ButtonStyle> button: {
        border-width: 0px,
        border-radius: 5px,
        filled: true,
        font-family: "",
        font-size: 16px,
        font-weight: 500,
        accent-text: false,
        margin-x: 4px,
        margin-y: 4px,
        padding-x: 14px,
        padding-y: 6px,
        depress: 4px,
        shadow-blur: 4px,
    };

    out property <ButtonStyle> button-boxy: {
        border-width: 2px,
        border-radius: 0px,
        filled: true,
        font-family: "",
        font-size: 16px,
        font-weight: 500,
        accent-text: true,
        margin-x: 4px,
        margin-y: 4px,
        padding-x: 14px,
        padding-y: 6px,
        depress: 4px,
        shadow-blur: 2px,
    };
}
