import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
  in-out property<int> counter: 0;
  callback request-counter-add(int);
  VerticalBox {
    Text {
      text: "Counter: \{root.counter}";
    }
    Button {
      text: "-1";
      clicked => {
        root.request-counter-add(+1);
      }
    }
    Button {
      text: "+1";
      clicked => {
        root.request-counter-add(-1);
      }
    }
  }
}
