export struct MaterialVariants {
    m: brush,
    m-50: brush,
    m-100: brush,
    m-200: brush,
    m-300: brush,
    m-400: brush,
    m-500: brush,
    m-600: brush,
    m-700: brush,
    m-800: brush,
    m-900: brush,
    m-A100: brush,
    m-A200: brush,
    m-A400: brush,
    m-A700: brush,
}

export global MaterialPalette {
    out property <MaterialVariants> red: {
        m: #f44336,
        m-50: #ffebee,
        m-100: #ffcdd2,
        m-200: #ef9a9a,
        m-300: #e57373,
        m-400: #ef5350,
        m-500: #f44336,
        m-600: #e53935,
        m-700: #d32f2f,
        m-800: #c62828,
        m-900: #b71c1c,
        m-A100: #ff8a80,
        m-A200: #ff5252,
        m-A400: #ff1744,
        m-A700: #d50000,
    };

    out property <MaterialVariants> pink: {
        m: #e91e63,
        m-50: #fce4ec,
        m-100: #f8bbd0,
        m-200: #f48fb1,
        m-300: #f06292,
        m-400: #ec407a,
        m-500: #e91e63,
        m-600: #d81b60,
        m-700: #c2185b,
        m-800: #ad1457,
        m-900: #880e4f,
        m-A100: #ff80ab,
        m-A200: #ff4081,
        m-A400: #f50057,
        m-A700: #c51162,
    };

    out property <MaterialVariants> purple: {
        m: #9c27b0,
        m-50: #f3e5f5,
        m-100: #e1bee7,
        m-200: #ce93d8,
        m-300: #ba68c8,
        m-400: #ab47bc,
        m-500: #9c27b0,
        m-600: #8e24aa,
        m-700: #7b1fa2,
        m-800: #6a1b9a,
        m-900: #4a148c,
        m-A100: #ea80fc,
        m-A200: #e040fb,
        m-A400: #d500f9,
        m-A700: #aa00ff,
    };

    out property <MaterialVariants> deepPurple: {
        m: #673ab7,
        m-50: #ede7f6,
        m-100: #d1c4e9,
        m-200: #b39ddb,
        m-300: #9575cd,
        m-400: #7e57c2,
        m-500: #673ab7,
        m-600: #5e35b1,
        m-700: #512da8,
        m-800: #4527a0,
        m-900: #311b92,
        m-A100: #b388ff,
        m-A200: #7c4dff,
        m-A400: #651fff,
        m-A700: #6200ea,
    };

    out property <MaterialVariants> indigo: {
        m: #3f51b5,
        m-50: #e8eaf6,
        m-100: #c5cae9,
        m-200: #9fa8da,
        m-300: #7986cb,
        m-400: #5c6bc0,
        m-500: #3f51b5,
        m-600: #3949ab,
        m-700: #303f9f,
        m-800: #283593,
        m-900: #1a237e,
        m-A100: #8c9eff,
        m-A200: #536dfe,
        m-A400: #3d5afe,
        m-A700: #304ffe,
    };

    out property <MaterialVariants> blue: {
        m: #2196f3,
        m-50: #e3f2fd,
        m-100: #bbdefb,
        m-200: #90caf9,
        m-300: #64b5f6,
        m-400: #42a5f5,
        m-500: #2196f3,
        m-600: #1e88e5,
        m-700: #1976d2,
        m-800: #1565c0,
        m-900: #0d47a1,
        m-A100: #82b1ff,
        m-A200: #448aff,
        m-A400: #2979ff,
        m-A700: #2962ff,
    };

    out property <MaterialVariants> lightBlue: {
        m: #03a9f4,
        m-50: #e1f5fe,
        m-100: #b3e5fc,
        m-200: #81d4fa,
        m-300: #4fc3f7,
        m-400: #29b6f6,
        m-500: #03a9f4,
        m-600: #039be5,
        m-700: #0288d1,
        m-800: #0277bd,
        m-900: #01579b,
        m-A100: #80d8ff,
        m-A200: #40c4ff,
        m-A400: #00b0ff,
        m-A700: #0091ea,
    };

    out property <MaterialVariants> cyan: {
        m: #00bcd4,
        m-50: #e0f7fa,
        m-100: #b2ebf2,
        m-200: #80deea,
        m-300: #4dd0e1,
        m-400: #26c6da,
        m-500: #00bcd4,
        m-600: #00acc1,
        m-700: #0097a7,
        m-800: #00838f,
        m-900: #006064,
        m-A100: #84ffff,
        m-A200: #18ffff,
        m-A400: #00e5ff,
        m-A700: #00b8d4,
    };

    out property <MaterialVariants> teal: {
        m: #009688,
        m-50: #e0f2f1,
        m-100: #b2dfdb,
        m-200: #80cbc4,
        m-300: #4db6ac,
        m-400: #26a69a,
        m-500: #009688,
        m-600: #00897b,
        m-700: #00796b,
        m-800: #00695c,
        m-900: #004d40,
        m-A100: #a7ffeb,
        m-A200: #64ffda,
        m-A400: #1de9b6,
        m-A700: #00bfa5,
    };

    out property <MaterialVariants> green: {
        m: #4caf50,
        m-50: #e8f5e9,
        m-100: #c8e6c9,
        m-200: #a5d6a7,
        m-300: #81c784,
        m-400: #66bb6a,
        m-500: #4caf50,
        m-600: #43a047,
        m-700: #388e3c,
        m-800: #2e7d32,
        m-900: #1b5e20,
        m-A100: #b9f6ca,
        m-A200: #69f0ae,
        m-A400: #00e676,
        m-A700: #00c853,
    };

    out property <MaterialVariants> lightGreen: {
        m: #8bc34a,
        m-50: #f1f8e9,
        m-100: #dcedc8,
        m-200: #c5e1a5,
        m-300: #aed581,
        m-400: #9ccc65,
        m-500: #8bc34a,
        m-600: #7cb342,
        m-700: #689f38,
        m-800: #558b2f,
        m-900: #33691e,
        m-A100: #ccff90,
        m-A200: #b2ff59,
        m-A400: #76ff03,
        m-A700: #64dd17,
    };

    out property <MaterialVariants> lime: {
        m: #cddc39,
        m-50: #f9fbe7,
        m-100: #f0f4c3,
        m-200: #e6ee9c,
        m-300: #dce775,
        m-400: #d4e157,
        m-500: #cddc39,
        m-600: #c0ca33,
        m-700: #afb42b,
        m-800: #9e9d24,
        m-900: #827717,
        m-A100: #f4ff81,
        m-A200: #eeff41,
        m-A400: #c6ff00,
        m-A700: #aeea00,
    };

    out property <MaterialVariants> yellow: {
        m: #ffeb3b,
        m-50: #fffde7,
        m-100: #fff9c4,
        m-200: #fff59d,
        m-300: #fff176,
        m-400: #ffee58,
        m-500: #ffeb3b,
        m-600: #fdd835,
        m-700: #fbc02d,
        m-800: #f9a825,
        m-900: #f57f17,
        m-A100: #ffff8d,
        m-A200: #ffff00,
        m-A400: #ffea00,
        m-A700: #ffd600,
    };

    out property <MaterialVariants> amber: {
        m: #ffc107,
        m-50: #fff8e1,
        m-100: #ffecb3,
        m-200: #ffe082,
        m-300: #ffd54f,
        m-400: #ffca28,
        m-500: #ffc107,
        m-600: #ffb300,
        m-700: #ffa000,
        m-800: #ff8f00,
        m-900: #ff6f00,
        m-A100: #ffe57f,
        m-A200: #ffd740,
        m-A400: #ffc400,
        m-A700: #ffab00,
    };

    out property <MaterialVariants> orange: {
        m: #ff9800,
        m-50: #fff3e0,
        m-100: #ffe0b2,
        m-200: #ffcc80,
        m-300: #ffb74d,
        m-400: #ffa726,
        m-500: #ff9800,
        m-600: #fb8c00,
        m-700: #f57c00,
        m-800: #ef6c00,
        m-900: #e65100,
        m-A100: #ffd180,
        m-A200: #ffab40,
        m-A400: #ff9100,
        m-A700: #ff6d00,
    };

    out property <MaterialVariants> deepOrange: {
        m: #ff5722,
        m-50: #fbe9e7,
        m-100: #ffccbc,
        m-200: #ffab91,
        m-300: #ff8a65,
        m-400: #ff7043,
        m-500: #ff5722,
        m-600: #f4511e,
        m-700: #e64a19,
        m-800: #d84315,
        m-900: #bf360c,
        m-A100: #ff9e80,
        m-A200: #ff6e40,
        m-A400: #ff3d00,
        m-A700: #dd2c00,
    };

    out property <MaterialVariants> brown: {
        m: #795548,
        m-50: #efebe9,
        m-100: #d7ccc8,
        m-200: #bcaaa4,
        m-300: #a1887f,
        m-400: #8d6e63,
        m-500: #795548,
        m-600: #6d4c41,
        m-700: #5d4037,
        m-800: #4e342e,
        m-900: #3e2723,
        m-A100: #d7ccc8,
        m-A200: #bcaaa4,
        m-A400: #8d6e63,
        m-A700: #5d4037,
    };

    out property <MaterialVariants> grey: {
        m: #9e9e9e,
        m-50: #fafafa,
        m-100: #f5f5f5,
        m-200: #eeeeee,
        m-300: #e0e0e0,
        m-400: #bdbdbd,
        m-500: #9e9e9e,
        m-600: #757575,
        m-700: #616161,
        m-800: #424242,
        m-900: #212121,
        m-A100: #f5f5f5,
        m-A200: #eeeeee,
        m-A400: #bdbdbd,
        m-A700: #616161,
    };

    out property <MaterialVariants> blueGrey: {
        m: #607d8b,
        m-50: #eceff1,
        m-100: #cfd8dc,
        m-200: #b0bec5,
        m-300: #90a4ae,
        m-400: #78909c,
        m-500: #607d8b,
        m-600: #546e7a,
        m-700: #455a64,
        m-800: #37474f,
        m-900: #263238,
        m-A100: #cfd8dc,
        m-A200: #b0bec5,
        m-A400: #78909c,
        m-A700: #455a64,
    };
}

export struct AccentPalette {
    normal: brush,
    faded: brush,
    bright: brush,
    background: brush,
    foreground: brush,
    special: brush,
}

export global MaterialScheme {
    in-out property <bool> dark-theme;

    in-out property <string> primary-accent-color: "teal";
    in-out property <string> secondary-accent-color: "deepOrange";

    out property <AccentPalette> primary-accent: scheme(primary-accent-color);
    out property <AccentPalette> secondary-accent: scheme(secondary-accent-color);

    pure function scheme(name: string) -> AccentPalette {
        if (name == "red") {
            {
                normal: MaterialPalette.red.m,
                faded: dark-theme ? MaterialPalette.red.m-700 : MaterialPalette.red.m-300,
                bright: dark-theme ? MaterialPalette.red.m-300 : MaterialPalette.red.m-700,
                background: dark-theme ? MaterialPalette.red.m-800 : MaterialPalette.red.m-200,
                foreground: dark-theme ? MaterialPalette.red.m-100 : MaterialPalette.red.m-900,
                special: dark-theme ? MaterialPalette.red.m-A700 : MaterialPalette.red.m-A100,
            }
        } else if (name == "pink") {
            {
                normal: MaterialPalette.pink.m,
                faded: dark-theme ? MaterialPalette.pink.m-700 : MaterialPalette.pink.m-300,
                bright: dark-theme ? MaterialPalette.pink.m-300 : MaterialPalette.pink.m-700,
                background: dark-theme ? MaterialPalette.pink.m-800 : MaterialPalette.pink.m-200,
                foreground: dark-theme ? MaterialPalette.pink.m-100 : MaterialPalette.pink.m-900,
                special: dark-theme ? MaterialPalette.pink.m-A700 : MaterialPalette.pink.m-A100,
            }
        } else if (name == "purple") {
            {
                normal: MaterialPalette.purple.m,
                faded: dark-theme ? MaterialPalette.purple.m-700 : MaterialPalette.purple.m-300,
                bright: dark-theme ? MaterialPalette.purple.m-300 : MaterialPalette.purple.m-700,
                background: dark-theme ? MaterialPalette.purple.m-800 : MaterialPalette.purple.m-200,
                foreground: dark-theme ? MaterialPalette.purple.m-100 : MaterialPalette.purple.m-900,
                special: dark-theme ? MaterialPalette.purple.m-A700 : MaterialPalette.purple.m-A100,
            }
        } else if (name == "deepPurple") {
            {
                normal: MaterialPalette.deepPurple.m,
                faded: dark-theme ? MaterialPalette.deepPurple.m-700 : MaterialPalette.deepPurple.m-300,
                bright: dark-theme ? MaterialPalette.deepPurple.m-300 : MaterialPalette.deepPurple.m-700,
                background: dark-theme ? MaterialPalette.deepPurple.m-800 : MaterialPalette.deepPurple.m-200,
                foreground: dark-theme ? MaterialPalette.deepPurple.m-100 : MaterialPalette.deepPurple.m-900,
                special: dark-theme ? MaterialPalette.deepPurple.m-A700 : MaterialPalette.deepPurple.m-A100,
            }
        } else if (name == "indigo") {
            {
                normal: MaterialPalette.indigo.m,
                faded: dark-theme ? MaterialPalette.indigo.m-700 : MaterialPalette.indigo.m-300,
                bright: dark-theme ? MaterialPalette.indigo.m-300 : MaterialPalette.indigo.m-700,
                background: dark-theme ? MaterialPalette.indigo.m-800 : MaterialPalette.indigo.m-200,
                foreground: dark-theme ? MaterialPalette.indigo.m-100 : MaterialPalette.indigo.m-900,
                special: dark-theme ? MaterialPalette.indigo.m-A700 : MaterialPalette.indigo.m-A100,
            }
        } else if (name == "blue") {
            {
                normal: MaterialPalette.blue.m,
                faded: dark-theme ? MaterialPalette.blue.m-700 : MaterialPalette.blue.m-300,
                bright: dark-theme ? MaterialPalette.blue.m-300 : MaterialPalette.blue.m-700,
                background: dark-theme ? MaterialPalette.blue.m-800 : MaterialPalette.blue.m-200,
                foreground: dark-theme ? MaterialPalette.blue.m-100 : MaterialPalette.blue.m-900,
                special: dark-theme ? MaterialPalette.blue.m-A700 : MaterialPalette.blue.m-A100,
            }
        } else if (name == "lightBlue") {
            {
                normal: MaterialPalette.lightBlue.m,
                faded: dark-theme ? MaterialPalette.lightBlue.m-700 : MaterialPalette.lightBlue.m-300,
                bright: dark-theme ? MaterialPalette.lightBlue.m-300 : MaterialPalette.lightBlue.m-700,
                background: dark-theme ? MaterialPalette.lightBlue.m-800 : MaterialPalette.lightBlue.m-200,
                foreground: dark-theme ? MaterialPalette.lightBlue.m-100 : MaterialPalette.lightBlue.m-900,
                special: dark-theme ? MaterialPalette.lightBlue.m-A700 : MaterialPalette.lightBlue.m-A100,
            }
        } else if (name == "cyan") {
            {
                normal: MaterialPalette.cyan.m,
                faded: dark-theme ? MaterialPalette.cyan.m-700 : MaterialPalette.cyan.m-300,
                bright: dark-theme ? MaterialPalette.cyan.m-300 : MaterialPalette.cyan.m-700,
                background: dark-theme ? MaterialPalette.cyan.m-800 : MaterialPalette.cyan.m-200,
                foreground: dark-theme ? MaterialPalette.cyan.m-100 : MaterialPalette.cyan.m-900,
                special: dark-theme ? MaterialPalette.cyan.m-A700 : MaterialPalette.cyan.m-A100,
            }
        } else if (name == "teal") {
            {
                normal: MaterialPalette.teal.m,
                faded: dark-theme ? MaterialPalette.teal.m-700 : MaterialPalette.teal.m-300,
                bright: dark-theme ? MaterialPalette.teal.m-300 : MaterialPalette.teal.m-700,
                background: dark-theme ? MaterialPalette.teal.m-800 : MaterialPalette.teal.m-200,
                foreground: dark-theme ? MaterialPalette.teal.m-100 : MaterialPalette.teal.m-900,
                special: dark-theme ? MaterialPalette.teal.m-A700 : MaterialPalette.teal.m-A100,
            }
        } else if (name == "green") {
            {
                normal: MaterialPalette.green.m,
                faded: dark-theme ? MaterialPalette.green.m-700 : MaterialPalette.green.m-300,
                bright: dark-theme ? MaterialPalette.green.m-300 : MaterialPalette.green.m-700,
                background: dark-theme ? MaterialPalette.green.m-800 : MaterialPalette.green.m-200,
                foreground: dark-theme ? MaterialPalette.green.m-100 : MaterialPalette.green.m-900,
                special: dark-theme ? MaterialPalette.green.m-A700 : MaterialPalette.green.m-A100,
            }
        } else if (name == "lightGreen") {
            {
                normal: MaterialPalette.lightGreen.m,
                faded: dark-theme ? MaterialPalette.lightGreen.m-700 : MaterialPalette.lightGreen.m-300,
                bright: dark-theme ? MaterialPalette.lightGreen.m-300 : MaterialPalette.lightGreen.m-700,
                background: dark-theme ? MaterialPalette.lightGreen.m-800 : MaterialPalette.lightGreen.m-200,
                foreground: dark-theme ? MaterialPalette.lightGreen.m-100 : MaterialPalette.lightGreen.m-900,
                special: dark-theme ? MaterialPalette.lightGreen.m-A700 : MaterialPalette.lightGreen.m-A100,
            }
        } else if (name == "lime") {
            {
                normal: MaterialPalette.lime.m,
                faded: dark-theme ? MaterialPalette.lime.m-700 : MaterialPalette.lime.m-300,
                bright: dark-theme ? MaterialPalette.lime.m-300 : MaterialPalette.lime.m-700,
                background: dark-theme ? MaterialPalette.lime.m-800 : MaterialPalette.lime.m-200,
                foreground: dark-theme ? MaterialPalette.lime.m-100 : MaterialPalette.lime.m-900,
                special: dark-theme ? MaterialPalette.lime.m-A700 : MaterialPalette.lime.m-A100,
            }
        } else if (name == "yellow") {
            {
                normal: MaterialPalette.yellow.m,
                faded: dark-theme ? MaterialPalette.yellow.m-700 : MaterialPalette.yellow.m-300,
                bright: dark-theme ? MaterialPalette.yellow.m-300 : MaterialPalette.yellow.m-700,
                background: dark-theme ? MaterialPalette.yellow.m-800 : MaterialPalette.yellow.m-200,
                foreground: dark-theme ? MaterialPalette.yellow.m-100 : MaterialPalette.yellow.m-900,
                special: dark-theme ? MaterialPalette.yellow.m-A700 : MaterialPalette.yellow.m-A100,
            }
        } else if (name == "amber") {
            {
                normal: MaterialPalette.amber.m,
                faded: dark-theme ? MaterialPalette.amber.m-700 : MaterialPalette.amber.m-300,
                bright: dark-theme ? MaterialPalette.amber.m-300 : MaterialPalette.amber.m-700,
                background: dark-theme ? MaterialPalette.amber.m-800 : MaterialPalette.amber.m-200,
                foreground: dark-theme ? MaterialPalette.amber.m-100 : MaterialPalette.amber.m-900,
                special: dark-theme ? MaterialPalette.amber.m-A700 : MaterialPalette.amber.m-A100,
            }
        } else if (name == "orange") {
            {
                normal: MaterialPalette.orange.m,
                faded: dark-theme ? MaterialPalette.orange.m-700 : MaterialPalette.orange.m-300,
                bright: dark-theme ? MaterialPalette.orange.m-300 : MaterialPalette.orange.m-700,
                background: dark-theme ? MaterialPalette.orange.m-800 : MaterialPalette.orange.m-200,
                foreground: dark-theme ? MaterialPalette.orange.m-100 : MaterialPalette.orange.m-900,
                special: dark-theme ? MaterialPalette.orange.m-A700 : MaterialPalette.orange.m-A100,
            }
        } else if (name == "deepOrange") {
            {
                normal: MaterialPalette.deepOrange.m,
                faded: dark-theme ? MaterialPalette.deepOrange.m-700 : MaterialPalette.deepOrange.m-300,
                bright: dark-theme ? MaterialPalette.deepOrange.m-300 : MaterialPalette.deepOrange.m-700,
                background: dark-theme ? MaterialPalette.deepOrange.m-800 : MaterialPalette.deepOrange.m-200,
                foreground: dark-theme ? MaterialPalette.deepOrange.m-100 : MaterialPalette.deepOrange.m-900,
                special: dark-theme ? MaterialPalette.deepOrange.m-A700 : MaterialPalette.deepOrange.m-A100,
            }
        } else if (name == "brown") {
            {
                normal: MaterialPalette.brown.m,
                faded: dark-theme ? MaterialPalette.brown.m-700 : MaterialPalette.brown.m-300,
                bright: dark-theme ? MaterialPalette.brown.m-300 : MaterialPalette.brown.m-700,
                background: dark-theme ? MaterialPalette.brown.m-800 : MaterialPalette.brown.m-200,
                foreground: dark-theme ? MaterialPalette.brown.m-100 : MaterialPalette.brown.m-900,
                special: dark-theme ? MaterialPalette.brown.m-A700 : MaterialPalette.brown.m-A100,
            }
        } else if (name == "grey") {
            {
                normal: MaterialPalette.grey.m,
                faded: dark-theme ? MaterialPalette.grey.m-700 : MaterialPalette.grey.m-300,
                bright: dark-theme ? MaterialPalette.grey.m-300 : MaterialPalette.grey.m-700,
                background: dark-theme ? MaterialPalette.grey.m-800 : MaterialPalette.grey.m-200,
                foreground: dark-theme ? MaterialPalette.grey.m-100 : MaterialPalette.grey.m-900,
                special: dark-theme ? MaterialPalette.grey.m-A700 : MaterialPalette.grey.m-A100,
            }
        } else if (name == "blueGrey") {
            {
                normal: MaterialPalette.blueGrey.m,
                faded: dark-theme ? MaterialPalette.blueGrey.m-700 : MaterialPalette.blueGrey.m-300,
                bright: dark-theme ? MaterialPalette.blueGrey.m-300 : MaterialPalette.blueGrey.m-700,
                background: dark-theme ? MaterialPalette.blueGrey.m-800 : MaterialPalette.blueGrey.m-200,
                foreground: dark-theme ? MaterialPalette.blueGrey.m-100 : MaterialPalette.blueGrey.m-900,
                special: dark-theme ? MaterialPalette.blueGrey.m-A700 : MaterialPalette.blueGrey.m-A100,
            }
        } else {
            {
                normal: #FF0000,
                faded: #00FFFF,
                bright: #FF00FF,
                background: #000000,
                foreground: #FFFFFF,
                special: #B00BE5
            }
        }
    }
}

